#!/bin/bash
#
#  AppExec: Bootstrap an Epichrome app
#
#  Copyright (C) 2022  David Marmor
#
#  https://github.com/dmarmor/epichrome
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# CORE APP INFO

# filled in by updateapp
SSBIdentifier=APPID


# ENSURE APP ISN'T ALREADY RUNNING (OR THIS IS A RELAUNCH), THEN FORK & TERMINATE

# unique ID tag for this app in the process table
idTag='--epichrome-id=APPID'
idGrep="$idTag"'([^-a-z0-9_]|$)'

if [[ "$1" = '--relaunch' ]] ; then
    # this is a relaunch, so don't check for the ID tag
    shift
else
    # if ID tag is in process table, we're already running
    if /usr/bin/pgrep -fiq -- "$idGrep" ; then
        
        # LOG FAILED LAUNCH
        
        # load core script
        myLogID=   # reset log ID
        source "${BASH_SOURCE[0]%/script}/Scripts/core.sh" 'coreDoInit=1' || exit 1
        [[ "$ok" ]] || abortreport
        
        # initialize log file
        initlogfile
        
        # try to get PID of running app
        runningPID=()
        try 'runningPID=(n)' /usr/bin/pgrep -fi -- "$idGrep" \
                'Unable to get PID of other app instance'
        ok=1 ; errmsg=
        
        # log failed launch
        errmsg='Cannot launch. Another instance of this app is already running'
        [[ "${runningPID[0]}" ]] && errmsg+=" at PID ${runningPID[0]}"
        errmsg+='.'
        errlog FATAL
        
        cleanexit
    fi
fi

# fork main script with ID tag
"${BASH_SOURCE[0]%/script}/Scripts/main.sh" "$idTag" "$@" < /dev/null &> /dev/null &
