#!/bin/bash
#
#  AppExec: Bootstrap an Epichrome app
#
#  Copyright (C) 2020  David Marmor
#
#  https://github.com/dmarmor/epichrome
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# ENSURE APP ISN'T ALREADY RUNNING, THEN FORK & TERMINATE

# unique ID tag for this app in the process table
idTag='--epichrome-id=APPID'

# check if tag is already in process table
/usr/bin/pgrep "$idTag" > /dev/null

# if tag isn't in process table, we're clear to launch
if [[ "$?" = 1 ]] ; then
        
    # fork main script with ID tag & kill parent app
    "${BASH_SOURCE[0]%/script}/Scripts/main.sh" "$idTag" "$@" &
    kill "$PPID"
fi
