#!/bin/sh
#
#  PlaceholderExec: Placeholder for an inactive app engine
#
#  Copyright (C) 2020  David Marmor
#
#  https://github.com/dmarmor/epichrome
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


# CORE APP INFO

SSBVersion='EPIVERSION'               # filled in by Makefile
SSBIdentifier=APPID                   # filled in by updateapp
CFBundleIdentifier=APPBUNDLEID        # filled in by updateapp


# CORE APP VARIABLES

myAppPath="{BASH_SOURCE[0]%/Contents/MacOS/*}"


# LOAD CORE SCRIPT

source "$myAppPath/Contents/Resources/Scripts/core.sh" || exit 1
myLogID="$myLogID|Placeholder"
[[ "$ok" ]] || abort

# ensure we have a data directory
[[ -d "$myDataPath" ]] || abort 'Unable to create data directory.'


# ATTEMPT TO LAUNCH PARENT APP

try /usr/bin/open -b "$CFBundleIdentifier" --args "$@" \
    'Unable to launch parent app.'
if [[ "$ok" ]] ; then
    debuglog 'Launched parent app.'
    exit 0
else
    # launch failed, so display error alert
    abort "$errmsg Unless you know what you're doing, you shouldn't try to launch the engine app directly anyway."
fi
